-- Switch to appropriate admin role
USE ROLE SECURITYADMIN;

-- Create a single role for DBT
CREATE OR REPLACE ROLE dbt_access_role;

-- Create a user for DBT and assign the role
CREATE OR REPLACE USER dbt_login_user
    PASSWORD = 'phanidbtaccess@66'
    DEFAULT_ROLE = dbt_access_role
    DEFAULT_WAREHOUSE = dbt_transforming
    COMMENT = 'User for DBT operations'
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE dbt_access_role TO USER dbt_login_user;

-- Switch to SYSADMIN to create objects
USE ROLE SYSADMIN;

-- Create a warehouse for DBT operations
CREATE OR REPLACE WAREHOUSE dbt_transforming
    WAREHOUSE_TYPE = 'STANDARD'
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create DBT-specific database and schema
CREATE OR REPLACE DATABASE SPOTIFY_DBT_DEV
    WITH COMMENT = 'Database for DBT operations';

CREATE OR REPLACE SCHEMA SPOTIFY_DBT_DEV.SPOTIFY_DBT_SCHEMA
    WITH COMMENT = 'Schema for DBT operations';

-- Grant full access to DBT role on its own database and schema
GRANT ALL ON DATABASE SPOTIFY_DBT_DEV TO ROLE dbt_access_role;
GRANT ALL ON SCHEMA SPOTIFY_DBT_DEV.SPOTIFY_DBT_SCHEMA TO ROLE dbt_access_role;
GRANT ALL ON WAREHOUSE dbt_transforming TO ROLE dbt_access_role;

-- Grant usage and read access to bronze/silver/gold layers
GRANT USAGE ON DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT USAGE ON DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT USAGE ON DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;

GRANT USAGE ON ALL SCHEMAS IN DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;

GRANT SELECT ON ALL TABLES IN DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT SELECT ON ALL TABLES IN DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT SELECT ON ALL TABLES IN DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;

GRANT SELECT ON ALL VIEWS IN DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT SELECT ON ALL VIEWS IN DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT SELECT ON ALL VIEWS IN DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;



-- Future-proof access
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;

GRANT SELECT ON FUTURE TABLES IN DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT SELECT ON FUTURE TABLES IN DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT SELECT ON FUTURE TABLES IN DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;

GRANT SELECT ON FUTURE VIEWS IN DATABASE SPOTIFY_BRONZE_DB TO ROLE dbt_access_role;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SPOTIFY_SILVER_DB TO ROLE dbt_access_role;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SPOTIFY_GOLD_DB TO ROLE dbt_access_role;
