--Change Default Role to Security Admin
USE ROLE SECURITYADMIN;

--Granting warehouse permissions to 
GRANT USAGE ON WAREHOUSE python_etl_wh TO ROLE python_access_role;

--Granting database and schema permissions to the role
GRANT USAGE ON DATABASE SPOTIFY_BRONZE_DB TO ROLE python_access_role;

GRANT USAGE ON SCHEMA SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA TO ROLE python_access_role;

--Granting permissions on objects in the schema
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA TO ROLE python_access_role;

GRANT READ,WRITE ON STAGE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE  TO ROLE python_access_role;
GRANT USAGE ON FILE FORMAT SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT  TO ROLE python_access_role;

--Granting permissions on pipes in the schema

GRANT OPERATE, MONITOR ON PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.USERS_BRONZE_PIPE TO ROLE python_access_role;

GRANT OPERATE, MONITOR ON PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SUBSCRIPTIONS_BRONZE_PIPE TO ROLE python_access_role;

GRANT OPERATE, MONITOR ON PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ARTISTS_BRONZE_PIPE TO ROLE python_access_role;

GRANT OPERATE, MONITOR ON PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ALBUMS_BRONZE_PIPE TO ROLE python_access_role;

GRANT OPERATE, MONITOR ON PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SONGS_BRONZE_PIPE TO ROLE python_access_role;

GRANT OPERATE, MONITOR ON PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.STREAM_ACTIVITY_BRONZE_PIPE TO ROLE python_access_role;

ALTER USER python_user_login SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA191VCxTwYnWrwAwoJfN0
ZHQXMu7zBNSgleD395GvBqwnodmzQvgBbCPhLSeYIAWdthSvBtflQvjMSVf7nxjw
Y7jvV+NfKSoEGP5ylwIj+ePiecWlAx95QfBcxoKeBHE//LU7OZrNbkZOCw6xUB9s
pdUfuFD+I3GXdK0RJmn6VwCDGQgUZT+L60qcHoePnr73RwTmb/thrAG2Pm32GmXf
nLAL+IAEXLEQMdZ1jB6ZaUOKRPj/AJleoX/wVXzTMBFFd9zOQK0h5mCo//6jnOM9
1x+J4djrkOE9vagTl1xMMCrCEfJFzTLiGZyIFlf4bEDSLA15W4VKbzHrxmW9jDMr
rQIDAQAB'; -- Replace with actual public key