USE ROLE SYSADMIN;

-- Create a Warehouse for Gold ETL operations

CREATE OR REPLACE WAREHOUSE GOLD_ETL_WH
WAREHOUSE_TYPE= 'STANDARD'
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE GOLD_ETL_WH;

-- Create Database and Schema for Gold Layer

CREATE OR REPLACE DATABASE SPOTIFY_GOLD_DB
WITH COMMENT = 'Database for Gold Layer of Spotify Data';

USE DATABASE SPOTIFY_GOLD_DB;

CREATE OR REPLACE SCHEMA SPOTIFY_GOLD_DB.SPOTIFY_GOLD_SCHEMA
WITH COMMENT = 'Schema for Gold Layer of Spotify Data';

USE DATABASE SPOTIFY_GOLD_DB;
USE SCHEMA SPOTIFY_GOLD_DB.SPOTIFY_GOLD_SCHEMA;

-- Create Tables for Gold Layer




