--Role Change to Sysadmin
USE ROLE SYSADMIN;

-- Create a Warehouse for Bronze ETL operations
-- This warehouse will be used for loading data into the Bronze layer
CREATE OR REPLACE WAREHOUSE BRONZE_ETL_WH
WAREHOUSE_TYPE= 'STANDARD'
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE BRONZE_ETL_WH;

-- Create Database and Schema for Bronze Layer
CREATE OR REPLACE DATABASE SPOTIFY_BRONZE_DB
WITH COMMENT = 'Database for Bronze Layer of Spotify Data';

USE DATABASE SPOTIFY_BRONZE_DB;
CREATE OR REPLACE SCHEMA SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA
WITH COMMENT = 'Schema for Bronze Layer of Spotify Data';

USE DATABASE SPOTIFY_BRONZE_DB;
USE SCHEMA SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA;

-- Create Tables for Bronze Layer

CREATE OR REPLACE TABLE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.USERS_BRONZE
(   
    user_id INT,
    name STRING,
    age STRING,
    email STRING,
    address STRING,
    device_type STRING,
    listening_time STRING,
    subscription_type STRING,
    subscription_category STRING
);


CREATE OR REPLACE TABLE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SUBSCRIPTIONS_BRONZE
(
    user_id INT,
    subscription_type STRING,
    subscription_category STRING,
    start_date DATE,
    end_date DATE,
    amount STRING
);


CREATE OR REPLACE TABLE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ARTISTS_BRONZE
(
    artist_id INT,
    name STRING,
    country STRING,
    popularity STRING,
    genre STRING
);

CREATE OR REPLACE TABLE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ALBUMS_BRONZE
(
    album_id INT,
    album_name STRING,
    release_date DATE,
    artist_id INT
);

CREATE OR REPLACE TABLE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SONGS_BRONZE
(
    song_id INT,
    name STRING,
    album STRING,
    album_id INT,
    artist_id INT,
    duration STRING,
    genre STRING
);


CREATE OR REPLACE TABLE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.STREAM_ACTIVITY_BRONZE 
(
    user_id INT,
    artist_id INT,
    song_id INT,
    play_count STRING,
    listening_time STRING,
    device_type STRING,
    album_id INT,
    timestamp TIMESTAMP,
    is_liked BOOLEAN,
    is_skipped BOOLEAN
);


-- Create a Stage and file format for Bronze Layer

CREATE OR REPLACE FILE FORMAT SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
COMPRESSION = 'AUTO'
WITH COMMENT = 'File format for Bronze Layer of Spotify Data';


CREATE OR REPLACE STAGE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT
WITH COMMENT = 'Stage for Bronze Layer of Spotify Data';

-- Create a Pipes for Bronze Layer 

CREATE OR REPLACE PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_PIPE
AS
COPY INTO SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.USERS_BRONZE
FROM @SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT)
FILE_PATTERN= '.*users.*\.csv'
ON_ERROR = 'CONTINUE'
WITH COMMENT = 'Pipe for Bronze Layer of Spotify Data';


CREATE OR REPLACE PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SUBSCRIPTIONS_BRONZE_PIPE
AS
COPY INTO SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SUBSCRIPTIONS_BRONZE
FROM @SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT)
FILE_PATTERN= '.*subscriptions.*\.csv'
ON_ERROR = 'CONTINUE'
WITH COMMENT = 'Pipe for Bronze Layer of Spotify Data';


CREATE OR REPLACE PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ARTISTS_BRONZE_PIPE
AS
COPY INTO SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ARTISTS_BRONZE
FROM @SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT)
FILE_PATTERN= '.*artists.*\.csv'
ON_ERROR = 'CONTINUE'
WITH COMMENT = 'Pipe for Bronze Layer of Spotify Data';


CREATE OR REPLACE PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ALBUMS_BRONZE_PIPE
AS
COPY INTO SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.ALBUMS_BRONZE
FROM @SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT)
FILE_PATTERN= '.*albums.*\.csv'
ON_ERROR = 'CONTINUE'
WITH COMMENT = 'Pipe for Bronze Layer of Spotify Data';

CREATE OR REPLACE PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SONGS_BRONZE_PIPE
AS
COPY INTO SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SONGS_BRONZE
FROM @SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT)
FILE_PATTERN= '.*songs.*\.csv'
ON_ERROR = 'CONTINUE'
WITH COMMENT = 'Pipe for Bronze Layer of Spotify Data';

CREATE OR REPLACE PIPE SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.STREAM_ACTIVITY_BRONZE_PIPE
AS
COPY INTO SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.STREAM_ACTIVITY_BRONZE
FROM @SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = SPOTIFY_BRONZE_DB.SPOTIFY_BRONZE_SCHEMA.SPOTIFY_BRONZE_FILE_FORMAT)
FILE_PATTERN= '.*stream_activity.*\.csv'
ON_ERROR = 'CONTINUE'
WITH COMMENT = 'Pipe for Bronze Layer of Spotify Data';








